/*
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s83765s83768.ui.internal.S83765s83768Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S83765s83768Activator.getInstance().getInjector("de.htwdd.sf.beleg.s83765s83768.Dsl");
	}

}
