/*
 * generated by Xtext 2.34.0
 */
package de.htwdd.sf.beleg.s83765s83768.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslUiModule extends AbstractDslUiModule {

	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
