/*
 * generated by Xtext 2.34.0
 */
package de.htwdd.sf.beleg.s83765s83768.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class DslProposalProvider extends AbstractDslProposalProvider {
}
