/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl.impl;

import de.htwdd.sf.beleg.s83765s83768.dsl.Action;
import de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.impl.ActionImpl#getNoun <em>Noun</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.impl.ActionImpl#getVi <em>Vi</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActionImpl extends MinimalEObjectImpl.Container implements Action
{
  /**
   * The default value of the '{@link #getNoun() <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoun()
   * @generated
   * @ordered
   */
  protected static final String NOUN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoun() <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoun()
   * @generated
   * @ordered
   */
  protected String noun = NOUN_EDEFAULT;

  /**
   * The default value of the '{@link #getVi() <em>Vi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVi()
   * @generated
   * @ordered
   */
  protected static final String VI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVi() <em>Vi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVi()
   * @generated
   * @ordered
   */
  protected String vi = VI_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNoun()
  {
    return noun;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNoun(String newNoun)
  {
    String oldNoun = noun;
    noun = newNoun;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ACTION__NOUN, oldNoun, noun));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVi()
  {
    return vi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVi(String newVi)
  {
    String oldVi = vi;
    vi = newVi;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.ACTION__VI, oldVi, vi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.ACTION__NOUN:
        return getNoun();
      case DslPackage.ACTION__VI:
        return getVi();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.ACTION__NOUN:
        setNoun((String)newValue);
        return;
      case DslPackage.ACTION__VI:
        setVi((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ACTION__NOUN:
        setNoun(NOUN_EDEFAULT);
        return;
      case DslPackage.ACTION__VI:
        setVi(VI_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.ACTION__NOUN:
        return NOUN_EDEFAULT == null ? noun != null : !NOUN_EDEFAULT.equals(noun);
      case DslPackage.ACTION__VI:
        return VI_EDEFAULT == null ? vi != null : !VI_EDEFAULT.equals(vi);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (noun: ");
    result.append(noun);
    result.append(", vi: ");
    result.append(vi);
    result.append(')');
    return result.toString();
  }

} //ActionImpl
