/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl.impl;

import de.htwdd.sf.beleg.s83765s83768.dsl.Benefit;
import de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Benefit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.impl.BenefitImpl#getNoun <em>Noun</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.impl.BenefitImpl#getPzvi <em>Pzvi</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BenefitImpl extends MinimalEObjectImpl.Container implements Benefit
{
  /**
   * The default value of the '{@link #getNoun() <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoun()
   * @generated
   * @ordered
   */
  protected static final String NOUN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoun() <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoun()
   * @generated
   * @ordered
   */
  protected String noun = NOUN_EDEFAULT;

  /**
   * The default value of the '{@link #getPzvi() <em>Pzvi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPzvi()
   * @generated
   * @ordered
   */
  protected static final String PZVI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPzvi() <em>Pzvi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPzvi()
   * @generated
   * @ordered
   */
  protected String pzvi = PZVI_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BenefitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.BENEFIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNoun()
  {
    return noun;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNoun(String newNoun)
  {
    String oldNoun = noun;
    noun = newNoun;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BENEFIT__NOUN, oldNoun, noun));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPzvi()
  {
    return pzvi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPzvi(String newPzvi)
  {
    String oldPzvi = pzvi;
    pzvi = newPzvi;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BENEFIT__PZVI, oldPzvi, pzvi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.BENEFIT__NOUN:
        return getNoun();
      case DslPackage.BENEFIT__PZVI:
        return getPzvi();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.BENEFIT__NOUN:
        setNoun((String)newValue);
        return;
      case DslPackage.BENEFIT__PZVI:
        setPzvi((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.BENEFIT__NOUN:
        setNoun(NOUN_EDEFAULT);
        return;
      case DslPackage.BENEFIT__PZVI:
        setPzvi(PZVI_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.BENEFIT__NOUN:
        return NOUN_EDEFAULT == null ? noun != null : !NOUN_EDEFAULT.equals(noun);
      case DslPackage.BENEFIT__PZVI:
        return PZVI_EDEFAULT == null ? pzvi != null : !PZVI_EDEFAULT.equals(pzvi);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (noun: ");
    result.append(noun);
    result.append(", pzvi: ");
    result.append(pzvi);
    result.append(')');
    return result.toString();
  }

} //BenefitImpl
