/*
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.htwdd.sf.beleg.s83765s83768.DslRuntimeModule;
import de.htwdd.sf.beleg.s83765s83768.DslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslIdeSetup extends DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule()));
	}
	
}
