/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Action#getNoun <em>Noun</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Action#getVi <em>Vi</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Noun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Noun</em>' attribute.
   * @see #setNoun(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getAction_Noun()
   * @model
   * @generated
   */
  String getNoun();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Action#getNoun <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Noun</em>' attribute.
   * @see #getNoun()
   * @generated
   */
  void setNoun(String value);

  /**
   * Returns the value of the '<em><b>Vi</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vi</em>' attribute.
   * @see #setVi(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getAction_Vi()
   * @model
   * @generated
   */
  String getVi();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Action#getVi <em>Vi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vi</em>' attribute.
   * @see #getVi()
   * @generated
   */
  void setVi(String value);

} // Action
