/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Benefit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Benefit#getNoun <em>Noun</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Benefit#getPzvi <em>Pzvi</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getBenefit()
 * @model
 * @generated
 */
public interface Benefit extends EObject
{
  /**
   * Returns the value of the '<em><b>Noun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Noun</em>' attribute.
   * @see #setNoun(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getBenefit_Noun()
   * @model
   * @generated
   */
  String getNoun();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Benefit#getNoun <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Noun</em>' attribute.
   * @see #getNoun()
   * @generated
   */
  void setNoun(String value);

  /**
   * Returns the value of the '<em><b>Pzvi</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pzvi</em>' attribute.
   * @see #setPzvi(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getBenefit_Pzvi()
   * @model
   * @generated
   */
  String getPzvi();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Benefit#getPzvi <em>Pzvi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pzvi</em>' attribute.
   * @see #getPzvi()
   * @generated
   */
  void setPzvi(String value);

} // Benefit
