/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Model#getStories <em>Stories</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Stories</b></em>' containment reference list.
   * The list contents are of type {@link de.htwdd.sf.beleg.s83765s83768.dsl.Story}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stories</em>' containment reference list.
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getModel_Stories()
   * @model containment="true"
   * @generated
   */
  EList<Story> getStories();

} // Model
