/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getTitle <em>Title</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getDp <em>Dp</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getBenefit <em>Benefit</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getRole <em>Role</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory()
 * @model
 * @generated
 */
public interface Story extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Title)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory_Title()
   * @model containment="true"
   * @generated
   */
  Title getTitle();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Title value);

  /**
   * Returns the value of the '<em><b>Dp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dp</em>' attribute.
   * @see #setDp(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory_Dp()
   * @model
   * @generated
   */
  String getDp();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getDp <em>Dp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dp</em>' attribute.
   * @see #getDp()
   * @generated
   */
  void setDp(String value);

  /**
   * Returns the value of the '<em><b>Benefit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Benefit</em>' containment reference.
   * @see #setBenefit(Benefit)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory_Benefit()
   * @model containment="true"
   * @generated
   */
  Benefit getBenefit();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getBenefit <em>Benefit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Benefit</em>' containment reference.
   * @see #getBenefit()
   * @generated
   */
  void setBenefit(Benefit value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' containment reference.
   * @see #setRole(Role)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory_Role()
   * @model containment="true"
   * @generated
   */
  Role getRole();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getRole <em>Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' containment reference.
   * @see #getRole()
   * @generated
   */
  void setRole(Role value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getStory_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Story#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

} // Story
