/**
 * generated by Xtext 2.35.0
 */
package de.htwdd.sf.beleg.s83765s83768.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Title#getNoun <em>Noun</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s83765s83768.dsl.Title#getVerb <em>Verb</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getTitle()
 * @model
 * @generated
 */
public interface Title extends EObject
{
  /**
   * Returns the value of the '<em><b>Noun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Noun</em>' attribute.
   * @see #setNoun(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getTitle_Noun()
   * @model
   * @generated
   */
  String getNoun();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Title#getNoun <em>Noun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Noun</em>' attribute.
   * @see #getNoun()
   * @generated
   */
  void setNoun(String value);

  /**
   * Returns the value of the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' attribute.
   * @see #setVerb(String)
   * @see de.htwdd.sf.beleg.s83765s83768.dsl.DslPackage#getTitle_Verb()
   * @model
   * @generated
   */
  String getVerb();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s83765s83768.dsl.Title#getVerb <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' attribute.
   * @see #getVerb()
   * @generated
   */
  void setVerb(String value);

} // Title
