/*
 * generated by Xtext 2.34.0
 */
package de.htwdd.sf.beleg.s83765s83768;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
