/*
 * generated by Xtext 2.34.0
 */
package de.htwdd.sf.beleg.s83765s83768.validation;


import org.eclipse.xtext.validation.Check;
import de.htwdd.sf.beleg.s83765s83768.dsl.Benefit;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DslValidator extends AbstractDslValidator {
	@Check
    public void checkPrefixZuVerbInfintivNoZuzu(Benefit benifit) {
        if (benifit.getPzvi() != null && benifit.getPzvi().contains("zuzu")) {
            error("The token PREFIX_ZU_VERB_INFINTIV cannot contain 'zuzu'.", benifit, null, -1);
        }
    }
}
